name: Docker Image CI

on: [push, release]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag local/varnish-prometheus-exporter
    
    - name: Push the Docker image
      if: github.event_name == 'release' && github.event.action == 'created'
      run: |
        docker tag local/varnish-prometheus-exporter squaremo/varnish-prometheus-exporter:${{ github.event.release.tag_name }}
        docker push squaremo/varnish-prometheus-exporter:${{ github.event.release.tag_name }}
